defaults:
  - model: lcnn
  - writer: noop
  - metrics: asvspoof
  - datasets: asvspoof_dummy
  - dataloader: asvspoof
  - transforms: asvspoof
  - _self_

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-3
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.9
  step_size: ${trainer.epoch_len}
loss_function:
  _target_: src.loss.CrossEntropyCM
dataloader:
  batch_size: 4
trainer:
  log_step: 1
  n_epochs: 1
  epoch_len: 2
  device_tensors: ["data_object", "labels"]
  resume_from: null
  device: cpu
  override: True
  monitor: "off"
  save_period: 1
  early_stop: 1
  save_dir: "saved"
  seed: 1
  max_grad_norm: 5.0
